apps/employees/urls.py
from django.conf.urls import url
from . import views

app_name = 'employees'

urlpatterns = [
    url(r'^$', views.HomeEmployeesView.as_view(), name='home'),
    url(r'menu/(?P<uuid>[-\w]+)/$', views.HomeEmployeesView.as_view(), name='home_uuid'),
    url(r'^menu/option/(?P<option_id>\d+)/customize/$', views.customize_order, name='custom_order'),
    url(r'^search-order/$', views.SearchOrderFormView.as_view(), name='search_order'),
]

apps/manager/urls.py
from django.conf.urls import url
from . import views

app_name = 'manager'

urlpatterns = [
    # url(r'^$', views.HomeMenuView.as_view(),name='home'),
    url(r'^$', views.MenuListView.as_view(), name='menu_list'),
    url(r'^dishes/$', views.DishListView.as_view(),name='dishes'),
    url(r'^dish/create/$', views.DishCreateView.as_view(),name='dish_create'),
    url(r'^dish/(?P<pk>\d+)/update/$', views.DishUpdateView.as_view(),name='dish_update'),
    url(r'^options/$', views.OptionListView.as_view(), name='option_list'),
    url(r'^option/create/$', views.option_create_edit, name='option_create'),
    url(r'^option/(?P<pk>\d+)/update$', views.option_create_edit, name='option_update'),
    url(r'^create/$', views.menu_option_create_edit, name='menu_create'),
    url(r'^orders/$', views.OrderListView.as_view(),name='order_list'),
    url(r'^order/(?P<pk>\d+)/details$', views.OrderDetailView.as_view(),name='order_details'),
    url(r'^(?P<pk>\d+)/update/$', views.menu_option_create_edit, name='menu_update'),
    url(r'^employees/$', views.EmployeeListView.as_view(),name='employee_list'),
]

backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url('admin/', admin.site.urls),
    url('^', include('apps.access.urls', namespace='access')),
    url('^', include('apps.employees.urls', namespace='employees')),
    url('^manager/', include('apps.manager.urls', namespace='manager')),
    url('^', include('apps.manager.api.urls', namespace='menu_api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/employees/models.py
from django.db import models
from apps.manager import models as menu_models


class Employee(models.Model):
    name = models.CharField(max_length=250)
    rut = models.CharField(max_length=10)
    email = models.EmailField(blank=True, null=True)
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'employee'
        managed = True

    def __str__(self):
        return self.name


class Order(models.Model):
    """Order model."""
    employee = models.ForeignKey(Employee, on_delete=models.DO_NOTHING,
                                 related_name='orders', blank=True, null=True)
    created_at = models.DateTimeField(auto_created=True)
    state = models.CharField(max_length=25, default='Pending')
    active = models.BooleanField(default=False)
    sale_price = models.DecimalField(max_digits=64, decimal_places=2, default=0)

    class Meta:
        db_table = 'order'
        managed = True

    def __str__(self):
        return str(self.id)


class Version(models.Model):
    """Version model"""
    name = models.CharField(max_length=50)
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'version'

    def __str__(self):
        return self.name


class OrderDetail(models.Model):
    """Order Detail model."""
    order = models.ForeignKey(Order, on_delete=models.DO_NOTHING,
                              blank=True, null=True, related_name='details')
    version = models.ForeignKey(Version, on_delete=models.DO_NOTHING, default=1)
    specification = models.TextField(blank=True, null=True)
    dish = models.ForeignKey(menu_models.Dish, on_delete=models.DO_NOTHING)

    class Meta:
        db_table = 'order_detail'
        verbose_name = 'Order Details'
        verbose_name_plural = 'Orders Details'

apps/employees/forms.py
from django import forms
from django.forms import inlineformset_factory

from apps.employees import models
from apps.commons.forms import BootstrapForm


class OrderDetailForm(forms.ModelForm, BootstrapForm):
    dish_name = forms.CharField()

    class Meta:
        model = models.OrderDetail
        fields = '__all__'
        widgets = {'dish': forms.HiddenInput()}

    def __init__(self, *args, **kwargs):
        super(OrderDetailForm, self).__init__(*args, **kwargs)
        self.empty_permitted = False
        self.fields['specification'].widget.attrs['rows'] = 2
        self.fields['dish_name'].widget.attrs['readonly'] = 'true'
        self.fields['specification'].label = 'Customizations'
        self.fields['specification'].widget.attrs['placeholder'] = 'Specify customizations'

        instance = kwargs.get('instance', None)
        if instance:
            self.initial['dish_name'] = instance.dish.name


class EmployeeForm(forms.ModelForm, BootstrapForm):
    class Meta:
        model = models.Employee
        exclude = ('active',)

    def __init__(self, *args, **kwargs):
        super(EmployeeForm, self).__init__(*args, **kwargs)
        self.fields['email'].help_text = 'Enter your email to receive ' \
                                         'notifications from our menus'


class SearchOrderForm(forms.Form):
    rut = forms.CharField(required=True, max_length=10, label='RUT')
    order_id = forms.IntegerField(required=True)

    def __init__(self, *args, **kwargs):
        super(SearchOrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

apps/employees/views.py
import datetime
from sqlite3 import IntegrityError

from django.contrib import messages
from django.db import transaction
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, render, redirect
from django.urls.base import reverse_lazy
from django.utils.html import format_html
from django.views import generic

from apps.manager import helpers as menu_helper
from apps.manager.models import Option
from . import forms
from . import helpers
from . import models


def customize_order(request, option_id, order_id=None):
    """Customize order."""
    template_name = 'employees/custom_order_form.html'
    option = get_object_or_404(Option, id=option_id)
    order = None
    details = None
    now = datetime.datetime.now()

    # comment this part of code for testing
    # time validation
    if now.hour >= 11:
        messages.info(request, 'Exceeded selection time(Until 11 am)')
        return redirect(reverse_lazy('employees:home'))
    # end time validation

    if order_id:
        order = get_object_or_404(models.Order, id=order_id)
        details = helpers.get_details_by_order_id(order_id)
    else:
        order = models.Order()
        order.sale_price = option.sale_price

    employee_form = forms.EmployeeForm(request.POST or None)

    order_detail_formset_factory = inlineformset_factory(
        models.Order,
        models.OrderDetail,
        form=forms.OrderDetailForm,
        can_delete=False,
        extra=len(option.options.all()),
        validate_min=True
    )
    formset = order_detail_formset_factory(
        request.POST or None,
        instance=order,
        prefix='formset_details',
        queryset=details
    )

    index = 0
    for subform in formset.forms:
        dish = option.options.all()[index].dish
        subform.initial = {
            'dish': dish,
            'dish_name': dish.name
        }
        index += 1

    if request.method == 'POST':
        print(request.POST)
        if formset.is_valid() and employee_form.is_valid():
            try:
                with transaction.atomic():
                    employee = employee_form.save(commit=False)
                    defaults = {
                        'name': employee.name,
                        'rut': employee.rut,
                        'email': employee.email
                    }
                    if helpers.exist_employee_order(employee):
                        raise IntegrityError('There is already an order today for this employee')
                    employee = helpers.update_or_create_employee(defaults, employee)
                    order.employee = employee
                    order.created_at = datetime.datetime.now()
                    order.save()
                    # Register options dishes
                    for frm in formset.forms:
                        print(frm.cleaned_data)
                        detail = frm.save(commit=False)
                        detail.order = order
                        detail.save()
            except IntegrityError as error:
                messages.error(request, format_html('An error has occurred: {0}'.format(error)))
            else:
                messages.success(request, "Successful action. Order ID: %s" % order.id)
                return render(request, 'employees/success.html', {'order': order})
        else:
            print(employee_form.errors)
            messages.error(request, 'Invalid forms')

    context = {
        'title': 'Custom you order',
        'formset': formset,
        'order': order,
        'option': option,
        'employee_form': employee_form
    }
    return render(request, template_name, context)


class HomeEmployeesView(generic.TemplateView):
    template_name = 'employees/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeEmployeesView, self).get_context_data(**kwargs)
        context['title'] = 'Home'
        uuid = kwargs.get('uuid')
        context['menu_options'] = menu_helper.get_menu_options_of_day(uuid or None)
        return context


class SearchOrderFormView(generic.FormView):
    form_class = forms.SearchOrderForm
    template_name = 'employees/search_order.html'
    success_url = reverse_lazy('employees:search_order')

    def get_context_data(self, **kwargs):
        context = super(SearchOrderFormView, self).get_context_data(**kwargs)
        context['title'] = 'Search order'
        return context

    def form_valid(self, form):
        data = form.cleaned_data
        rut = data.get('rut')
        order_id = data.get('order_id')
        order = helpers.get_order_by_rut_and_id(rut, order_id)
        if not order:
            messages.info(self.request, format_html('Opss!!! <br> Order not found'))
        context = {
            'order': order,
            'form': self.get_form(),
            'title': 'Search order'
        }
        return render(self.request, 'employees/search_order.html/', context)

apps/employees/templates/employees/custom_order_form.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
    {{ block.super }} {{ title }}
{% endblock %}

{% block styles %}
    <style>
        hr:last-of-type {
            display: none;
        }

        .div-actions {
            border-top: 1px solid #EEEEEE;
            padding-top: 10px;
        }
    </style>
{% endblock %}

{% block navbar %}
    {% include 'employees/navbar.html' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            {% include 'layout/messages.html' %}
            <form method="post" novalidate>
                <legend>Customize {{ option.name }}</legend>
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-12">
                        {{ employee_form.as_p }}
                    </div>
                </div>
                <hr>
                {{ formset.management_form }}
                {% for frm in formset %}
                    <div class="row">
                        <div class="col-md-12">
                            {{ frm.as_p }} <br>
                        </div>
                    </div>
                    <hr>
                {% endfor %}

                <div class="row">
                    <div class="col-md-12 div-actions">

                        {% if order.state == 'Pending' %}
                            <button type="submit" class="btn btn-primary pull-right">
                                {% if object.pk %}
                                    Update
                                {% else %}
                                    Save
                                {% endif %}
                            </button>
                        {% endif %}
                        <a href="{% url 'employees:home' %}" class="btn btn-default">Cancel</a>
                        {% if order.state == 'Draft' and  order.pk %}
                            <button type="submit" class="btn btn-success" name="btn_confirm">Confirm</button>
                        {% endif %}
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

apps/employees/templates/employees/home.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
    {{ block.super }} {{ title }}
{% endblock %}

{% block navbar %}
    {% include 'employees/navbar.html' %}
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h2 class="text-center">Cornershop's Backend Test</h2>
        <img src="{% static 'images/food.jpg' %}" alt="" class="img-responsive">
    </div>

    <div class="row">
    <h1 class="text-center">MENU
       {% comment %} {% if menu_options %}
            <span>{{ menu_options.0.menu.name }}</span>
        {% endif %}{% endcomment %}
        <br> .................
    </h1>
    {% include 'layout/messages.html' %}
    {% if menu_options %}
            {% for obj in menu_options %}
                <div class="col-lg-4 text-center card">
                    <img class="img-circle"
                         src="{% static 'images/dish-1.png' %}"
                         alt="Generic placeholder image" width="140" height="140">
                    <h2>{{ obj.option.name }}</h2>
                    <p>{{ obj.option.chef_recommendations | truncatechars:120 }}</p>
                    <ul class="text-center" style="padding: 0; margin: 0">
                        {% for obj in obj.option.options.all %}
                            <li>
                                <strong>{{ obj.dish }}</strong> <br>
                                <i>{{ obj.dish.ingredients }}</i>
                            </li><br>
                        {% endfor %}
                    </ul>
                    <p>
                        <a class="btn btn-default" href="{% url 'employees:custom_order' option_id=obj.option.id %}"
                          role="button">Customize »</a>
                    </p>
                </div>
            {% endfor %}
        {% else %}
        <p class="text-center">Today's menu has not been created</p>
    {% endif %}
    </div>

{% endblock %}

apps/employees/templates/employees/navbar.html
{% load static %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'employees:home' %}">
                <img alt="Brand" height="20" src="{% static 'images/favicon.ico' %}" width="20">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li {% if request.resolver_match.url_name == 'home' %}class="active"{% endif %}><a href="{% url 'employees:home' %}">Home</span></a></li>
                <li {% if request.resolver_match.url_name == 'search_order' %}class="active"{% endif %}><a href="{% url 'employees:search_order' %}">Check your order</span></a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'manager:menu_list' %}" target="_blank"> <i class="fa fa-cutlery fa-lg"></i> Admin Menus</a></li>
                {% endif %}
                {% include 'layout/partial_login.html' %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

apps/employees/templates/employees/search_order.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
    {{ block.super }} {{ title }}
{% endblock %}

{% block navbar %}
    {% include 'employees/navbar.html' %}
{% endblock %}

{% block content %}
    <div class="row" id="search-wrapper">
        <div class="col-md-4 col-md-offset-4">
            <form method="post" novalidate>
                <legend>Check your order</legend>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
            <div>
                <br>
                {% include 'layout/messages.html' %}
            </div>
            {% if order %}
                <hr>
                <div class="row">
                    <div class="col-md-12">
                        <h3>{{ order.employee }} </h3>
                        <h5>{{ order.created_at }}</h5>
                        {% for detail in order.details.all %}
                            <p>
                                {{ detail.dish }}
                                {% if detail.specification %}
                                    ({{ detail.specification }})
                                {% endif %}
                            </p>
                        {% endfor %}
                    <p><b>State:</b> <span class="label label-info">{{ order.state }}</span></p>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

apps/employees/templates/employees/success.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
    {{ block.super }} {{ title }}
{% endblock %}

{% block navbar %}
    {% include 'employees/navbar.html' %}
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h2 class="text-center">Cornershop's Backend Test</h2>
        <img src="{% static 'images/food.jpg' %}" alt="" class="img-responsive">
    </div>

    <div class="row">
        <div class="col-md-12">
            {% include 'layout/messages.html' %}
            <h1 class="text-center">Order ID: {{ order.id }} <br> .................... </h1>
            <p class="text-center">Thanks for using our services</p>
            <p class="text-center"> Sincerely, <br>
                Cornershop's Team
            </p>
        </div>
    </div>

{% endblock %}