apps/access/urls.py
from django.contrib.auth.views import logout_then_login
from django.conf.urls import url
from . import views

app_name = 'access'

urlpatterns = [
    url(r'^login/$', views.LoginTemplateView.as_view(), name='login'),
    url(r'^signup/$', views.RegisterView.as_view(), name='signup'),
    url(r'^logout$', logout_then_login, {'next_page': '/',}, name='logout'),
]

backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url('admin/', admin.site.urls),
    url('^', include('apps.access.urls', namespace='access')),
    url('^', include('apps.employees.urls', namespace='employees')),
    url('^manager/', include('apps.manager.urls', namespace='manager')),
    url('^', include('apps.manager.api.urls', namespace='menu_api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/commons/models.py
from django.db import models

# Create your models here.

apps/commons/forms.py
from django import forms


class BootstrapForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(BootstrapForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

apps/commons/views.py
from django.shortcuts import render

# Create your views here.

apps/commons/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'layout/meta.html' %}
    <link rel="shortcut icon" href="https://superpal.s3.amazonaws.com/static/landings/img/favicon.ico">
    {% include 'layout/global_stylesheets.html' %}

    {% block styles %}{% endblock %}
    <title>{% block title %}Cornershop's | {% endblock %}</title>
</head>
<body>

{% block navbar %}{% endblock %}

<div class="container">
    {% block content %}{% endblock %}
</div>

{% include 'layout/footer.html' %}
{% include 'layout/global_scripts.html' %}

{% block js_script_bottom %}{% endblock %}

</body>
</html>

apps/commons/templates/layout/footer.html
<footer>
    <div class="container">
        <br>
        <br>
        <br>
        <p class="text-center">
            <i class="fa fa-copyright"></i> Todos los derechos reservados - Cornershop's Backend Test - {% now "SHORT_DATETIME_FORMAT" %}
        </p>
    </div>
</footer>

apps/commons/templates/layout/global_scripts.html
{% load static %}
<!-- jQuery -->
<script src="{% static 'vendors/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap -->
<script src="{% static 'vendors/bootstrap/js/bootstrap.min.js' %}"></script>

apps/commons/templates/layout/global_stylesheets.html
{% load static %}
<!-- Bootstrap -->
<link href="{% static 'vendors/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">

<link href="{% static 'css/cornershop.css' %}" rel="stylesheet">

apps/commons/templates/layout/messages.html
{% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'debug' %}info{% else %}{{ message.tags }}{% endif %}"
                 role="alert">
                <button type="button" class="close" data-dismiss="alert"><span>×</span></button>
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}

apps/commons/templates/layout/meta.html
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="Cornershop's Backend Test">
<meta name="author" content="Ing. Santiago D. Alvarez Reyes">

apps/commons/templates/layout/partial_login.html
{% if user.is_authenticated %}
    <li><a href="/admin/" target="_blank"> <i class="fa fa-database fa-lg"></i> Admin</a></li>
    <li><a href="{% url 'access:logout' %}"> <i class="fa fa-sign-out fa-lg"></i> Log out</a></li>
    <li><a href="javascript:void(0)"> {{ user }}</a></li>
{% else %}
    <li><a href="{% url 'access:login' %}"><i class="fa fa-sign-in fa-lg"></i> Sign in</a></li>
{% endif %}

apps/commons/templates/layout/template_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cornershop's Backend Test</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 12px;
        }

        .container {
            margin: 0 auto;
            width: 600px;
        }

        table {
            width: 100%;
            page-break-inside: auto;
            font-size: 12px;
            border-collapse: collapse;
        }

        table th,
        table td, .resumen table td {
            border: 1px solid #ddd !important;
            margin: 0 !important;
            padding: 5px;
        }

        ol {
            float: right;
            text-align: right;
        }

        ol > li {
            list-style: none;
        }

        .text-footer {
            border-top: 1px solid #ddd !important;
            padding-top: 5px;
            text-align: center;
            font-size: 10px;
            font-style: italic;
        }
    </style>
</head>
<body>
<div class="container">
    <p>
        Check the menu of day: <br>
        <a href="https://nora.cornershop.io/menu/{{ uuid }}/">https://nora.cornershop.io/menu/{{ uuid }}</a> <br>
    
        <i>Test link: </i> <a href="http://localhost:8000/menu/{{ uuid }}/">http://localhost:8000/menu/{{ uuid }}</a> <br>

        Sincerely, <br>
        Cornershop's Team
    </p>

    <p class="text-footer">
        Cornershop's Backend Test {% now 'd/m/Y H:i' %}
    </p>
</div>
</body>
</html>