apps/employees/urls.py
from django.conf.urls import url
from . import views

app_name = 'employees'

urlpatterns = [
    url(r'^$', views.HomeEmployeesView.as_view(), name='home'),
    url(r'menu/(?P<uuid>[-\w]+)/$', views.HomeEmployeesView.as_view(), name='home_uuid'),
    url(r'^menu/option/(?P<option_id>\d+)/customize/$', views.customize_order, name='custom_order'),
    url(r'^search-order/$', views.SearchOrderFormView.as_view(), name='search_order'),
]

apps/manager/api/urls.py
from django.conf.urls import url
from apps.manager.api import api

app_name = 'menu'

urlpatterns = [
    url(r'^api/order/update/$', api.change_order_state),
]

apps/manager/urls.py
from django.conf.urls import url
from . import views

app_name = 'manager'

urlpatterns = [
    # url(r'^$', views.HomeMenuView.as_view(),name='home'),
    url(r'^$', views.MenuListView.as_view(), name='menu_list'),
    url(r'^dishes/$', views.DishListView.as_view(),name='dishes'),
    url(r'^dish/create/$', views.DishCreateView.as_view(),name='dish_create'),
    url(r'^dish/(?P<pk>\d+)/update/$', views.DishUpdateView.as_view(),name='dish_update'),
    url(r'^options/$', views.OptionListView.as_view(), name='option_list'),
    url(r'^option/create/$', views.option_create_edit, name='option_create'),
    url(r'^option/(?P<pk>\d+)/update$', views.option_create_edit, name='option_update'),
    url(r'^create/$', views.menu_option_create_edit, name='menu_create'),
    url(r'^orders/$', views.OrderListView.as_view(),name='order_list'),
    url(r'^order/(?P<pk>\d+)/details$', views.OrderDetailView.as_view(),name='order_details'),
    url(r'^(?P<pk>\d+)/update/$', views.menu_option_create_edit, name='menu_update'),
    url(r'^employees/$', views.EmployeeListView.as_view(),name='employee_list'),
]

backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url('admin/', admin.site.urls),
    url('^', include('apps.access.urls', namespace='access')),
    url('^', include('apps.employees.urls', namespace='employees')),
    url('^manager/', include('apps.manager.urls', namespace='manager')),
    url('^', include('apps.manager.api.urls', namespace='menu_api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/manager/forms.py
from django import forms
from django.forms import inlineformset_factory

from apps.commons.forms import BootstrapForm
from apps.manager import models


class DishForm(forms.ModelForm, BootstrapForm):
    class Meta:
        model = models.Dish
        exclude = ('user',)


class OptionForm(forms.ModelForm, BootstrapForm):
    class Meta:
        model = models.Option
        exclude = ('user',)


class OptionDishForm(forms.ModelForm, BootstrapForm):
    class Meta:
        model = models.OptionDish
        exclude = ("option",)


class MenuForm(forms.ModelForm, BootstrapForm):
    class Meta:
        model = models.Menu
        exclude = ('user', 'state', 'effective_date', 'uuid')


class MenuOptionForm(forms.ModelForm, BootstrapForm):
    class Meta:
        model = models.MenuOption
        exclude = ('menu',)


OptionDishFormsetFactory = inlineformset_factory(
    models.Option,
    models.OptionDish,
    form=OptionDishForm,
    can_delete=True,
    extra=0,
    min_num=1,
    validate_min=True
)

MenuOptionFormsetFactory = inlineformset_factory(
    models.Menu,
    models.MenuOption,
    form=MenuOptionForm,
    can_delete=True,
    extra=0,
    min_num=1,
    validate_min=True
)

apps/manager/views.py
from sqlite3 import IntegrityError

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db import transaction
from django.shortcuts import get_object_or_404, render, redirect
from django.urls.base import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.html import format_html
from django.views import generic

from apps.access.decorators import user_has_permission
from apps.employees import models as employee_models
from apps.manager import forms
from apps.manager import helpers
from apps.manager import models


@method_decorator(user_has_permission, name='dispatch')
class HomeMenuView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'manager/home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeMenuView, self).get_context_data(**kwargs)
        context['title'] = 'home'
        return context


@method_decorator(user_has_permission, name='dispatch')
class DishCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'manager/dish_form.html'
    form_class = forms.DishForm
    success_url = reverse_lazy('manager:dishes')

    def get_context_data(self, **kwargs):
        context = super(DishCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Create dish'
        return context

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()
        return super(DishCreateView, self).form_valid(form)


@method_decorator(user_has_permission, name='dispatch')
class DishUpdateView(generic.UpdateView):
    template_name = 'manager/dish_form.html'
    form_class = forms.DishForm
    queryset = models.Dish.objects.all()
    success_url = reverse_lazy('manager:dishes')

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()
        return super(DishUpdateView, self).form_valid(form)


@method_decorator(user_has_permission, name='dispatch')
class DishListView(LoginRequiredMixin, generic.ListView):
    template_name = 'manager/dish_list.html'
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        context['title'] = 'Dishes'
        context['groups'] = helpers.get_groups()
        context['orders'] = helpers.get_orders()

        return context

    def get_queryset(self):
        params = self.request.GET
        self.queryset = helpers.get_all_dishes(params)
        return self.queryset


@method_decorator(user_has_permission, name='dispatch')
class OptionListView(LoginRequiredMixin, generic.ListView):
    template_name = 'manager/option_list.html'
    queryset = models.Option.objects.all()
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super(OptionListView, self).get_context_data(**kwargs)
        context['title'] = 'Options'
        return context

    def get_queryset(self):
        params = self.request.GET
        self.queryset = helpers.get_all_options(params)
        return self.queryset


@method_decorator(user_has_permission, name='dispatch')
class MenuListView(LoginRequiredMixin, generic.ListView):
    template_name = 'manager/menu_list.html'
    paginate_by = 25

    def get_queryset(self):
        params = self.request.GET
        return helpers.get_all_menus(params)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MenuListView, self).get_context_data(**kwargs)
        context['title'] = 'Menus'
        return context


@method_decorator(user_has_permission, name='dispatch')
class OrderListView(LoginRequiredMixin, generic.ListView):
    template_name = 'manager/order_list.html'
    paginate_by = 20

    def get_queryset(self):
        params = self.request.GET
        print(params)
        if 'criteria' in params.keys():
            return helpers.get_all_orders(params.get('criteria'))
        return helpers.get_all_orders(None)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(OrderListView, self).get_context_data(**kwargs)
        context['title'] = 'Employee orders'
        return context


@method_decorator(user_has_permission, name='dispatch')
class OrderDetailView(LoginRequiredMixin, generic.DetailView):
    model = employee_models.Order
    queryset = employee_models.Order.objects.all()
    template_name = 'manager/order_details.html'

    def get_context_data(self, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        context['title'] = 'Order Details'
        context['details'] = None
        return context


@method_decorator(user_has_permission, name='dispatch')
class EmployeeListView(LoginRequiredMixin, generic.ListView):
    template_name = 'manager/employee_list.html'
    paginate_by = 25

    def get_queryset(self):
        params = self.request.GET
        if 'criteria' in params.keys():
            return helpers.get_all_employees(params.get('criteria'))
        return helpers.get_all_employees(None)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(EmployeeListView, self).get_context_data(**kwargs)
        context['title'] = 'Employees'
        return context


@login_required
@user_has_permission
def option_create_edit(request, pk=None):
    template_name = 'manager/option_form.html'
    option = models.Option()
    queryset_option_dish = None
    if pk:
        option = get_object_or_404(models.Option, pk=pk)
        queryset_option_dish = helpers.get_option_dishes(option)
    form = forms.OptionForm(request.POST or None, instance=option)

    formset_option_dish = forms.OptionDishFormsetFactory(
        request.POST or None,
        instance=option,
        queryset=queryset_option_dish,
        prefix='frm_option_dish'
    )
    if request.method == 'POST':
        if form.is_valid() and formset_option_dish.is_valid():
            try:
                with transaction.atomic():
                    option = form.save(commit=False)
                    option.user = request.user
                    option.save()
                    # Register options dishes
                    for frm in formset_option_dish.forms:
                        if frm.cleaned_data.get('DELETE') and frm.instance.pk:
                            frm.instance.delete()
                        else:
                            option_dish = frm.save(commit=False)
                            option_dish.option = option
                            option_dish.save()
            except IntegrityError as error:
                messages.error(request, format_html('An error has occurred {0}'.format(error)))
            else:
                messages.success(request, "Successful action")
                return redirect('manager:option_list')
        else:
            print(form.errors)
            print(formset_option_dish.errors)
            messages.error(request, 'Invalid forms')

    context = {
        'form': form,
        'formset': formset_option_dish
    }
    return render(request, template_name, context)


@login_required
@user_has_permission
def menu_option_create_edit(request, pk=None):
    template_name = 'manager/menu_option_form.html'
    menu = models.Menu()
    queryset_menu_option = None
    if pk:
        menu = get_object_or_404(models.Menu, pk=pk)
        queryset_menu_option = helpers.get_all_menu_option(menu)
    form = forms.MenuForm(request.POST or None, instance=menu)

    formset_menu_option = forms.MenuOptionFormsetFactory(
        request.POST or None,
        instance=menu,
        queryset=queryset_menu_option,
        prefix='frm_menu_option'
    )
    if request.method == 'POST':
        if form.is_valid() and formset_menu_option.is_valid():
            try:
                with transaction.atomic():
                    menu = form.save(commit=False)
                    menu.user = request.user
                    menu.save()
                    # Register menu options dishes
                    for frm in formset_menu_option.forms:
                        if frm.cleaned_data.get('DELETE') and frm.instance.pk:
                            frm.instance.delete()
                        else:
                            menu_option = frm.save(commit=False)
                            menu_option.menu = menu
                            menu_option.save()
                    if 'btn_confirm' in request.POST:
                        menu.state = 'Confirm'
                        menu.save()

            except IntegrityError as error:
                messages.error(request, format_html('An error has occurred {0}'.format(error)))
            else:
                messages.success(request, "Successful action")
                return redirect('manager:menu_list')
        else:
            messages.error(request, 'Invalid forms')
    context = {
        'form': form,
        'formset': formset_menu_option,
        'menu': menu
    }
    return render(request, template_name, context)

apps/manager/templates/manager/dish_form.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
    {{ block.super }} {{ title }}
{% endblock %}

{% block navbar %}
    {% include 'manager/navbar.html' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <form action="" method="post" novalidate>
                {% csrf_token %}
                <legend>Dish Form</legend>
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary pull-right">
                    {% if object.pk %}
                        Update
                        {% else %}
                        Save
                    {% endif %}
                </button>
                <a href="{% url 'manager:dishes' %}" class="btn btn-default">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

apps/manager/templates/manager/dish_list.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
    {{ block.super }} {{ title }}
{% endblock %}

{% block navbar %}
    {% include 'manager/navbar.html' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box-tools">
                <form action="" method="GET" class="form-inline">
                    <select name="select_group" class="form-control" id="select-group">
                        <option value="none"> -- Groups --</option>
                        {% for group in groups %}
                            <option value="{{ group.name | lower }}"
                                    {% if request.GET.select_group == group.name.lower %}selected{% endif %}>{{ group.name | upper }}</option>
                        {% endfor %}
                    </select>
                    <select name="select_order" class="form-control" id="select-order">
                        <option value="none"> -- Orders --</option>
                        {% for order in orders %}
                            <option value="{{ order.name | lower }}"
                                    {% if request.GET.select_order == order.name.lower %}selected{% endif %}>{{ order.name | upper }}</option>
                        {% endfor %}
                    </select>
                    <input type="text" name="criteria" class="form-control" maxlength="20"
                           placeholder="Filter"
                           value="{% if request.GET.criteria %}{{ request.GET.criteria }}{% endif %}">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                    <a href="{% url 'manager:dish_create' %}" class="btn btn-default"><i class="fa fa-plus"></i></a>
                </form>
            </div>
            <br>
        </div>
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Code</th>
                        <th>Order</th>
                        <th>Date</th>
                        <th>Active</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for dish in object_list %}
                        <tr onclick=" location='{% url 'manager:dish_update' pk=dish.id %}'" class="tr-link">
                            <td>{{ dish.name }}</td>
                            <td>{{ dish.code }}</td>
                            <td>{{ dish.order }}</td>
                            <td>{{ dish.created_at }}</td>
                            <td>{{ dish.active }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% if is_paginated %}
                <div class="box-footer clearfix text-center">
                    <ul class="pagination pagination-sm no-margin">
                        {% if page_obj.has_previous %}
                            <a href="{% url 'manager:dishes' %}?page={{ page_obj.previous_page_number }}{% if request.GET.select_group %}&select_group={{ request.GET.select_group }}{% endif %}{% if request.GET.select_order %}&select_order={{ request.GET.select_order }}{% endif %}{% if request.GET.criteria %}&criteria={{ request.GET.criteria }}{% endif %}">Previous</a>
                        {% endif %}
                        <span class="current">
                                    Page {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                                </span>
                        {% if page_obj.has_next %}
                            <a href="{% url 'manager:dishes' %}?page={{ page_obj.next_page_number }}{% if request.GET.select_group %}&select_group={{ request.GET.select_group }}{% endif %}{% if request.GET.select_order %}&select_order={{ request.GET.select_order }}{% endif %}{% if request.GET.criteria %}&criteria={{ request.GET.criteria }}{% endif %}">Next</a>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block js_script_bottom %}
    <script src="{% static 'js/dish_list.js' %}"></script>
{% endblock %}

apps/manager/templates/manager/home.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
    {{ block.super }} {{ title }}
{% endblock %}

{% block navbar %}
    {% include 'manager/navbar.html' %}
{% endblock %}

{% block content %}
    <h1>Menu Admin</h1>
{% endblock %}

apps/manager/templates/manager/menu_list.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
    {{ block.super }} {{ title }}
{% endblock %}

{% block navbar %}
    {% include 'manager/navbar.html' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% include 'layout/messages.html' %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box-tools">
                <form action="" method="GET" class="form-inline">
                    <input type="text" name="criteria" class="form-control" maxlength="20"
                           placeholder="Filter"
                           value="{% if request.GET.criteria %}{{ request.GET.criteria }}{% endif %}">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                    <a href="{% url 'manager:menu_create' %}" class="btn btn-default"><i class="fa fa-plus"></i></a>
                </form>
            </div>
            <br>
        </div>
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Chef</th>
                        <th>State</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in object_list %}
                        <tr onclick=" location='{% url 'manager:menu_update' pk=obj.id %}'" class="tr-link">
                            <td>{{ obj.name }}</td>
                            <td>{{ obj.chef }}</td>
                            <td>{{ obj.uuid }}</td>
                            <td>
                                <span class="label {% if obj.state == 'Draft' %}label-danger{% else %}label-success{% endif %}">{{ obj.state }}</span>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% if is_paginated %}
                <div class="box-footer clearfix text-center">
                    <ul class="pagination pagination-sm no-margin">
                        {% if page_obj.has_previous %}
                            <a href="{% url 'manager:menu_list' %}?page={{ page_obj.previous_page_number }}{% if request.GET.criteria %}&criteria={{ request.GET.criteria }}{% endif %}">Previous</a>
                        {% endif %}
                        <span class="current">
                            Page {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="{% url 'manager:menu_list' %}?page={{ page_obj.next_page_number }}{% if request.GET.criteria %}&criteria={{ request.GET.criteria }}{% endif %}">Next</a>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block js_script_bottom %}
    <script src="{%  static 'js/menu_list.js' %}"></script>
{% endblock %}

apps/manager/templates/manager/navbar.html
{% load static %}
<nav class="navbar navbar-default navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'manager:menu_list' %}">
                <img alt="Brand" height="20" src="{% static 'images/favicon.ico' %}" width="20">
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li {% if request.resolver_match.url_name == 'menu_list' %}class="active"{% endif %}><a
                        href="{% url 'manager:menu_list' %}">Menus</a></li>
                <li {% if request.resolver_match.url_name == 'option_list' %}class="active"{% endif %}><a
                        href="{% url 'manager:option_list' %}">Menu Options</a></li>
                <li {% if request.resolver_match.url_name == 'dishes' %}class="active"{% endif %}><a
                        href="{% url 'manager:dishes' %}">Dishes</a></li>
                <li {% if request.resolver_match.url_name == 'order_list' %}class="active"{% endif %}><a
                        href="{% url 'manager:order_list' %}">Orders</a></li>
                <li {% if request.resolver_match.url_name == 'employee_list' %}class="active"{% endif %}><a
                        href="{% url 'manager:employee_list' %}">Employees</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'employees:home' %}" target="_blank"> <i class="fa fa-internet-explorer fa-lg"></i> Web Site</a></li>
                {% include 'layout/partial_login.html' %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

apps/manager/templates/manager/option_list.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
    {{ block.super }} {{ title }}
{% endblock %}

{% block navbar %}
    {% include 'manager/navbar.html' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% include 'layout/messages.html' %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box-tools">
                <form action="" method="GET" class="form-inline">
                    <input type="text" name="criteria" class="form-control" maxlength="20"
                           placeholder="Filter"
                           value="{% if request.GET.criteria %}{{ request.GET.criteria }}{% endif %}">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                    <a href="{% url 'manager:option_create' %}" class="btn btn-default"><i class="fa fa-plus"></i></a>
                </form>
            </div>
            <br>
        </div>
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Code</th>
                        <th>Menu</th>
                        <th>Price</th>
                        <th>Active</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in object_list %}
                        <tr onclick=" location='{% url 'manager:option_update' pk=obj.id %}'" class="tr-link">
                            <td>{{ obj.name }}</td>
                            <td>{{ obj.code }}</td>
                            <td>{{ obj.menu }}</td>
                            <td>{{ obj.sale_price }}</td>
                            <td>{{ obj.active }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% if is_paginated %}
                <div class="box-footer clearfix text-center">
                    <ul class="pagination pagination-sm no-margin">
                        {% if page_obj.has_previous %}
                            <a href="{% url 'manager:option_list' %}?page={{ page_obj.previous_page_number }}{% if request.GET.select_menu %}&select_menu={{ request.GET.select_menu }}{% endif %}{% if request.GET.criteria %}&criteria={{ request.GET.criteria }}{% endif %}">Previous</a>
                        {% endif %}
                        <span class="current">
                            Page {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="{% url 'manager:option_list' %}?page={{ page_obj.next_page_number }}{% if request.GET.select_menu %}&select_menu={{ request.GET.select_menu }}{% endif %}{% if request.GET.criteria %}&criteria={{ request.GET.criteria }}{% endif %}">Next</a>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block js_script_bottom %}
    <script src="{% static 'js/option_list.js' %}"></script>
{% endblock %}

apps/manager/templates/manager/order_list.html
{% extends 'layout/base.html' %}

{% load static %}

{% block title %}
    {{ block.super }} {{ title }}
{% endblock %}

{% block navbar %}
    {% include 'manager/navbar.html' %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% include 'layout/messages.html' %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box-tools">
                <form action="" method="GET" class="form-inline">
                    <input type="text" name="criteria" class="form-control" maxlength="20"
                           placeholder="Filter by employee name"
                           value="{% if request.GET.criteria %}{{ request.GET.criteria }}{% endif %}">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                    <a href="{% url 'manager:menu_create' %}" class="btn btn-default"><i class="fa fa-plus"></i></a>
                </form>
            </div>
            <br>
        </div>
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Employee</th>
                        <th>Employee RUT</th>
                        <th>Date</th>
                        <th>Sale Price</th>
                        <th>State</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in object_list %}
                        <tr onclick=" location='{% url 'manager:order_details' pk=obj.id %}'" class="tr-link">
                            <td>{{ obj.id}}</td>
                            <td>{{ obj.employee}}</td>
                            <td>{{ obj.employee.rut}}</td>
                            <td>{{ obj.created_at}}</td>
                            <td>{{ obj.sale_price }}</td>
                            <td>
                                <span class="label {% if obj.state == 'Pending' %}label-danger{% else %}label-success{% endif %}">{{ obj.state }}</span>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% if is_paginated %}
                <div class="box-footer clearfix text-center">
                    <ul class="pagination pagination-sm no-margin">
                        {% if page_obj.has_previous %}
                            <a href="{% url 'manager:order_list' %}?page={{ page_obj.previous_page_number }}{% if request.GET.criteria %}&criteria={{ request.GET.criteria }}{% endif %}">Previous</a>
                        {% endif %}
                        <span class="current">
                            Page {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="{% url 'manager:order_list' %}?page={{ page_obj.next_page_number }}{% if request.GET.criteria %}&criteria={{ request.GET.criteria }}{% endif %}">Next</a>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}