apps/access/urls.py
from django.contrib.auth.views import logout_then_login
from django.conf.urls import url
from . import views

app_name = 'access'

urlpatterns = [
    url(r'^login/$', views.LoginTemplateView.as_view(), name='login'),
    url(r'^signup/$', views.RegisterView.as_view(), name='signup'),
    url(r'^logout$', logout_then_login, {'next_page': '/',}, name='logout'),
]

backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url('admin/', admin.site.urls),
    url('^', include('apps.access.urls', namespace='access')),
    url('^', include('apps.employees.urls', namespace='employees')),
    url('^manager/', include('apps.manager.urls', namespace='manager')),
    url('^', include('apps.manager.api.urls', namespace='menu_api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/access/models.py
from django.contrib.auth.models import User
from django.db import models
from .signals import assign_role

models.signals.post_save.connect(assign_role, sender=User)

apps/access/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username',)

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

apps/access/views.py
from django.contrib.auth import views as auth_views
from django.urls.base import reverse_lazy
from django.views import generic

from . import forms


class LoginTemplateView(auth_views.LoginView):
    """Login View."""
    template_name = 'login.html'
    redirect_field_name = 'next'

    def get_success_url(self):
        if self.request.user.groups.filter(name__iexact='admin').exists() \
                or self.request.user.is_superuser:
            return reverse_lazy('manager:menu_list')
        elif self.request.user.groups.filter(name__iexact='clients').exists():
            return reverse_lazy('employees:home')


class RegisterView(generic.CreateView):
    """Signup view."""
    form_class = forms.RegisterForm
    template_name = 'register.html'
    success_url = reverse_lazy('access:login')

apps/access/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'layout/meta.html' %}

    <title>Cornershop's | Login</title>

    {% include 'layout/global_stylesheets.html' %}

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">

</head>

<body>

<div class="container">

    <form class="form-signin" method="post" novalidate>
        {% csrf_token %}
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="id_username" class="sr-only">Email address</label>
        <input type="text" name="username" autofocus="" maxlength="254" required="" id="id_username"
               class="form-control" placeholder="Username">
        {{ form.username.errors }}
        <input type="hidden" name="next" value="{{ request.GET.next }}"/>
        <label for="id_password" class="sr-only">Password</label>
        <input type="password" name="password" id="id_password" placeholder="Password" class="form-control">
        {{ form.password.errors }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <p class="text-center">
            <br>
            <a href="{% url 'access:signup' %}">New customer? Start here.</a>
        </p>
        {% if form.non_field_errors %}
            <br>
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Error!</strong> <br>
                <ul class='form-errors'>
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </form>
</div> <!-- /container -->
</body>
</html>

apps/access/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'layout/meta.html' %}

    <title>Cornershop's | Login</title>

    {% include 'layout/global_stylesheets.html' %}

    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
    <link href="{% static 'css/cornershop.css' %}" rel="stylesheet">
    <link href="{% static 'vendors/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
</head>

<body>

<div class="container">
    <form class="form-signin" method="post" novalidate>
        {% csrf_token %}
        <h2 class="form-signin-heading">Please sign up</h2>
        {{ form.as_table }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
        {% if form.non_field_errors %}
            <br>
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Error!</strong> <br>
                <ul class='form-errors'>
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        <p class="text-center">
            <br>
            <a href="{% url 'access:login' %}">Already have an account? Sign in <i class="fa fa-pull-right"></i> </a>
        </p>
    </form>
</div> <!-- /container -->
</body>
</html>